name: Daily Stock Sync

on:
  schedule:
    # 北京时间 16:05 运行（UTC 时间 8:05）
    - cron: '05 8 * * *'
  workflow_dispatch:  # 允许手动触发

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run stock script
      env:
        TUSHARE_TOKEN: ${{ secrets.TUSHARE_TOKEN }}
        FEISHU_APP_ID: ${{ secrets.FEISHU_APP_ID }}
        FEISHU_APP_SECRET: ${{ secrets.FEISHU_APP_SECRET }}
        FEISHU_APP_TOKEN: ${{ secrets.FEISHU_APP_TOKEN }}
        FEISHU_TABLE_ID: ${{ secrets.FEISHU_TABLE_ID }}
      run: python fetch_stocks.py
